[package]
name = "infer-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
test-backends = []

[dependencies]
infer-core.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
