[package]
name = "infer-scheduler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ahash.workspace = true
infer-core.workspace = true
infer-ir.workspace = true
infer-spi.workspace = true
serde.workspace = true
serde_json.workspace = true
