//! Fixed device activations and captured, model-independent tensor operations.
pub(crate) mod arena;
mod batch;
pub use batch::BatchOutput;
mod attention;
mod attention_decode;
mod attention_prefill;
mod batch_projection;
mod capture;
mod capture_attention;
mod capture_rope;
mod capture_state;
mod fp8_cache;
mod fp8_gemm;
mod kernels;
mod linear_batch;
mod metadata;
mod nvfp4_gemm;
mod prefill_gemm;
mod prefill_projection;
mod profile;
mod program;
mod recurrent;
mod recurrent_prefill;
pub(crate) mod slot_batch;
mod slot_verify;
mod small_gemm;
mod validation;
pub use arena::ActivationArena;
pub use program::{DeviceProgram, FusionWeights, ProgramWeights};

mod conv_prefill;
